"""Tenant lifecycle constants and helpers (Onboarding 2.0, DEC-032)."""

from __future__ import annotations

LIFECYCLE_DRAFT = "draft"
LIFECYCLE_ONBOARDING = "onboarding"
LIFECYCLE_WAITING_FOR_CUSTOMER = "waiting_for_customer"
LIFECYCLE_TECHNICAL_VERIFICATION = "technical_verification"
LIFECYCLE_READY_FOR_ACTIVATION = "ready_for_activation"
LIFECYCLE_ACTIVE = "active"
LIFECYCLE_ARCHIVED = "archived"

VALID_LIFECYCLE_STATUSES: frozenset[str] = frozenset(
    {
        LIFECYCLE_DRAFT,
        LIFECYCLE_ONBOARDING,
        LIFECYCLE_WAITING_FOR_CUSTOMER,
        LIFECYCLE_TECHNICAL_VERIFICATION,
        LIFECYCLE_READY_FOR_ACTIVATION,
        LIFECYCLE_ACTIVE,
        LIFECYCLE_ARCHIVED,
    }
)

# Non-destructive transitions (operations+). Archive/restore handled separately (admin).
ALLOWED_LIFECYCLE_TRANSITIONS: dict[str, frozenset[str]] = {
    LIFECYCLE_DRAFT: frozenset({LIFECYCLE_ONBOARDING}),
    LIFECYCLE_ONBOARDING: frozenset(
        {LIFECYCLE_WAITING_FOR_CUSTOMER, LIFECYCLE_TECHNICAL_VERIFICATION, LIFECYCLE_READY_FOR_ACTIVATION}
    ),
    LIFECYCLE_WAITING_FOR_CUSTOMER: frozenset({LIFECYCLE_TECHNICAL_VERIFICATION, LIFECYCLE_ONBOARDING}),
    LIFECYCLE_TECHNICAL_VERIFICATION: frozenset(
        {LIFECYCLE_READY_FOR_ACTIVATION, LIFECYCLE_WAITING_FOR_CUSTOMER}
    ),
    LIFECYCLE_READY_FOR_ACTIVATION: frozenset({LIFECYCLE_ACTIVE, LIFECYCLE_TECHNICAL_VERIFICATION}),
    LIFECYCLE_ACTIVE: frozenset({LIFECYCLE_ARCHIVED}),
    LIFECYCLE_ARCHIVED: frozenset({LIFECYCLE_ACTIVE, LIFECYCLE_ONBOARDING}),
}

LIFECYCLE_LABELS_SV: dict[str, str] = {
    LIFECYCLE_DRAFT: "Utkast",
    LIFECYCLE_ONBOARDING: "Onboarding",
    LIFECYCLE_WAITING_FOR_CUSTOMER: "Väntar på kund",
    LIFECYCLE_TECHNICAL_VERIFICATION: "Teknisk verifiering",
    LIFECYCLE_READY_FOR_ACTIVATION: "Redo för aktivering",
    LIFECYCLE_ACTIVE: "Aktiv",
    LIFECYCLE_ARCHIVED: "Arkiverad",
}
